global:
  scrape_interval: 10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'go-api'
    static_configs:
      - targets: ['api:2112']
        labels:
          service: 'go-api-application'
    metrics_path: '/metrics'
