global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'go-api'
    static_configs:
      - targets: ['api:2112']
        labels:
          service: 'go-api-application'
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
