version: "3.9"

services:
  postgres:
    image: postgres:17.5-alpine3.22
    hostname: postgres
    container_name: urlshort_postgres_container
    ports:
      - 5435:5432
    volumes:
      - urlshort_pgdata:/var/lib/postgresql/data/pgdata
      - ../migrations/psql:/docker-entrypoint-initdb.d
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASS}
      POSTGRES_DB: ${POSTGRES_DBNAME}
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: unless-stopped
    networks:
      - urlshort_net
  redis:
    image: redis:latest
    container_name: urlshort_redis_container
    hostname: redis
    ports:
      - 6379:6379
    volumes:
      - urlshort_redis_data:/data
    env_file:
      - .env
    command: redis-server --save 60 1 --loglevel warning --requirepass ${REDIS_PASS}
    networks:
      - urlshort_net
    restart: unless-stopped
  api:
    image: urlshort/api
    build:
      context: ../
      dockerfile: deploy/api/DockerFile
    container_name: urlshort_api_container
    environment:
      WAIT_HOSTS: postgres:5432
    depends_on:
      - postgres
      - redis
    ports:
      - 8091:8080
      - 2112:2112
    restart: always
    networks:
      - urlshort_net
      - urlshort_metrics
    
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ../config/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - urlshort_metrics
  
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - urlshort_grafana_storage:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASS}
      GF_USERS_ALLOW_SIGN_UP: false
    depends_on:
      - prometheus
    networks:
      - urlshort_metrics
volumes:
  urlshort_pgdata:
  urlshort_redis_data:
  urlshort_grafana_storage:

networks:
  urlshort_net:
  urlshort_metrics: