name: Ci

on: 
    push:
        branches: [ "main" ]
    pull_request:
        branches: ["main", "dev"]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        outputs:
          go-cache-key: ${{steps.cache-go-mod.outputs.cache-key}}
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup GO
              uses: actions/setup-go@v4
              with:
                go-version: '1.24.4'
            - name: Cache Go modules
              id: cache-go-mod
              uses: actions/cache@v3
              with:
                path: |
                  ~/go/pkg/mod
                  ./go.sum
                key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
                restore-keys: |
                  ${{ runner.os }}-go-

            - name: Download dependencies
              if: steps.cache-go-mod.outputs.cache-hit != 'true'
              run: go mod download

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Restore Go cache
              uses: actions/cache@v3
              with:
                path: |
                  ~/go/pkg/mod
                  ./go.sum
                key: ${{ needs.setup.outputs.go-cache-key }}
            - name: Setup Go (reuse from setup job)
              uses: actions/setup-go@v4
              with:
                go-version: '1.24.4'
                cache: true
            - name: Run tests
              working-directory: ${{ github.workspace }} 
              run: |
                go test ./internal/stats
                go test ./internal/url_cache_manager
                go test ./internal/url_manager
