name: Ci

on: 
    push:
        branches: [ "main" ]
    pull_request:
        branches: ["main", "dev"]
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - name: Setup GO
              uses: actions/setup-go@v4
              with:
                go-version: '1.24.4'

            - name: Download dependencies
              run: go mod download

    test:
        runs-on: ubuntu-latest
        needs: build
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Run tests
              working-directory: ${{ github.workspace }} 
              run: |
                go test ./internal/stats
                go test ./internal/url_cache_manager
                go test ./internal/url_manager
