name: CD

on:
    workflow_run:
      workflows: ["Ci"]
      types: 
        - completed
    workflow_dispatch:

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Load configs
              run: |
                mkdir -p config deploy
                echo "${{secrets.APP_CONFIG}}" > ./config/cfg.yaml
                echo "${{secrets.SERVICES_ENV}}" > ./deploy/.env
            - name: Upload configs
              uses: appleboy/scp-action@v1
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USERNAME }}
                key: ${{ secrets.SSH_KEY }}
                source: "config/cfg.yaml,deploy/.env"
                target: "/home/${{secrets.SSH_USERNAME}}/apps/url_shortener/"
                strip_components: 0
                tar_exec: tar
                debug: true
            - name: Deploy via SSH
              uses: appleboy/ssh-action@v1
              with:
                host: ${{secrets.SSH_HOST}}
                username: ${{secrets.SSH_USERNAME}}
                key: ${{secrets.SSH_KEY}}
                script: |
                  cd ~/apps/url_shortener
                  git fetch origin
                  git checkout main
                  git reset --hard origin/main
                  cd ./deploy
                  docker compose down
                  docker compose up -d --build
                  docker image prune -f
